
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.k7a2.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.k7a2.block.K7A2WoodWoodBlock;
import net.mcreator.k7a2.block.K7A2WoodStairsBlock;
import net.mcreator.k7a2.block.K7A2WoodSlabBlock;
import net.mcreator.k7a2.block.K7A2WoodPlanksBlock;
import net.mcreator.k7a2.block.K7A2WoodLogBlock;
import net.mcreator.k7a2.block.K7A2WoodLeavesBlock;
import net.mcreator.k7a2.block.K7A2WoodFenceGateBlock;
import net.mcreator.k7a2.block.K7A2WoodFenceBlock;
import net.mcreator.k7a2.block.K7A2SecretDecorationBlock;
import net.mcreator.k7a2.block.K7A2RainbowDecorationBlockBlock;
import net.mcreator.k7a2.block.K7A2RainbowBlockBlock;
import net.mcreator.k7a2.block.K7A2PortalBlockBlock;
import net.mcreator.k7a2.block.K7A2LavaBlock;
import net.mcreator.k7a2.block.K7A2FlowerBlock;
import net.mcreator.k7a2.block.K7A2DimPortalBlock;
import net.mcreator.k7a2.block.DHPhucWoodBlock;
import net.mcreator.k7a2.block.DHPhucStairsBlock;
import net.mcreator.k7a2.block.DHPhucSlabBlock;
import net.mcreator.k7a2.block.DHPhucPlanksBlock;
import net.mcreator.k7a2.block.DHPhucLogBlock;
import net.mcreator.k7a2.block.DHPhucLeavesBlock;
import net.mcreator.k7a2.block.DHPhucFenceGateBlock;
import net.mcreator.k7a2.block.DHPhucFenceBlock;
import net.mcreator.k7a2.block.BlockofK7A2Block;
import net.mcreator.k7a2.block.BlockofHaMinhBlock;
import net.mcreator.k7a2.block.BlockOfVuThaoBlock;
import net.mcreator.k7a2.block.BlockOfVhlinhBlock;
import net.mcreator.k7a2.block.BlockOfUyenBlock;
import net.mcreator.k7a2.block.BlockOfTrucBlock;
import net.mcreator.k7a2.block.BlockOfTplinhBlock;
import net.mcreator.k7a2.block.BlockOfThlinhBlock;
import net.mcreator.k7a2.block.BlockOfThlinh2Block;
import net.mcreator.k7a2.block.BlockOfThanhBlock;
import net.mcreator.k7a2.block.BlockOfThaiBlock;
import net.mcreator.k7a2.block.BlockOfTaiBlock;
import net.mcreator.k7a2.block.BlockOfQuynhBlock;
import net.mcreator.k7a2.block.BlockOfPhuongBlock;
import net.mcreator.k7a2.block.BlockOfNhatMinhBlock;
import net.mcreator.k7a2.block.BlockOfNguyenPhucBlock;
import net.mcreator.k7a2.block.BlockOfNguyenMinhBlock;
import net.mcreator.k7a2.block.BlockOfNguyenLinhBlock;
import net.mcreator.k7a2.block.BlockOfNguyenBlock;
import net.mcreator.k7a2.block.BlockOfNgocAnhBlock;
import net.mcreator.k7a2.block.BlockOfNganBlock;
import net.mcreator.k7a2.block.BlockOfMyAnBlock;
import net.mcreator.k7a2.block.BlockOfLamBlock;
import net.mcreator.k7a2.block.BlockOfKieuThaoBlock;
import net.mcreator.k7a2.block.BlockOfKhanhsBlock;
import net.mcreator.k7a2.block.BlockOfKhanhBlock;
import net.mcreator.k7a2.block.BlockOfHoaiAnBlock;
import net.mcreator.k7a2.block.BlockOfHaiBlock;
import net.mcreator.k7a2.block.BlockOfGiangBlock;
import net.mcreator.k7a2.block.BlockOfDuongMinhBlock;
import net.mcreator.k7a2.block.BlockOfDuongBlock;
import net.mcreator.k7a2.block.BlockOfDucAnhBlock;
import net.mcreator.k7a2.block.BlockOfDiepBlock;
import net.mcreator.k7a2.block.BlockOfDatBlock;
import net.mcreator.k7a2.block.BlockOfDanhBlock;
import net.mcreator.k7a2.block.BlockOfDangMinhBlock;
import net.mcreator.k7a2.block.BlockOfDHPBlock;
import net.mcreator.k7a2.block.BlockOfCoToanBlock;
import net.mcreator.k7a2.block.BlockOfChauBlock;
import net.mcreator.k7a2.block.AetherPortalBlock;
import net.mcreator.k7a2.K7a2Mod;

public class K7a2ModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, K7a2Mod.MODID);
	public static final RegistryObject<Block> BLOCKOF_K_7_A_2 = REGISTRY.register("blockof_k_7_a_2", () -> new BlockofK7A2Block());
	public static final RegistryObject<Block> K_7_A_2_WOOD_WOOD = REGISTRY.register("k_7_a_2_wood_wood", () -> new K7A2WoodWoodBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_LOG = REGISTRY.register("k_7_a_2_wood_log", () -> new K7A2WoodLogBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_PLANKS = REGISTRY.register("k_7_a_2_wood_planks", () -> new K7A2WoodPlanksBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_LEAVES = REGISTRY.register("k_7_a_2_wood_leaves", () -> new K7A2WoodLeavesBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_STAIRS = REGISTRY.register("k_7_a_2_wood_stairs", () -> new K7A2WoodStairsBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_SLAB = REGISTRY.register("k_7_a_2_wood_slab", () -> new K7A2WoodSlabBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_FENCE = REGISTRY.register("k_7_a_2_wood_fence", () -> new K7A2WoodFenceBlock());
	public static final RegistryObject<Block> K_7_A_2_WOOD_FENCE_GATE = REGISTRY.register("k_7_a_2_wood_fence_gate", () -> new K7A2WoodFenceGateBlock());
	public static final RegistryObject<Block> K_7_A_2_DIM_PORTAL = REGISTRY.register("k_7_a_2_dim_portal", () -> new K7A2DimPortalBlock());
	public static final RegistryObject<Block> K_7_A_2_PORTAL_BLOCK = REGISTRY.register("k_7_a_2_portal_block", () -> new K7A2PortalBlockBlock());
	public static final RegistryObject<Block> DH_PHUC_WOOD = REGISTRY.register("dh_phuc_wood", () -> new DHPhucWoodBlock());
	public static final RegistryObject<Block> DH_PHUC_LOG = REGISTRY.register("dh_phuc_log", () -> new DHPhucLogBlock());
	public static final RegistryObject<Block> DH_PHUC_PLANKS = REGISTRY.register("dh_phuc_planks", () -> new DHPhucPlanksBlock());
	public static final RegistryObject<Block> DH_PHUC_LEAVES = REGISTRY.register("dh_phuc_leaves", () -> new DHPhucLeavesBlock());
	public static final RegistryObject<Block> DH_PHUC_STAIRS = REGISTRY.register("dh_phuc_stairs", () -> new DHPhucStairsBlock());
	public static final RegistryObject<Block> DH_PHUC_SLAB = REGISTRY.register("dh_phuc_slab", () -> new DHPhucSlabBlock());
	public static final RegistryObject<Block> DH_PHUC_FENCE = REGISTRY.register("dh_phuc_fence", () -> new DHPhucFenceBlock());
	public static final RegistryObject<Block> DH_PHUC_FENCE_GATE = REGISTRY.register("dh_phuc_fence_gate", () -> new DHPhucFenceGateBlock());
	public static final RegistryObject<Block> AETHER_PORTAL = REGISTRY.register("aether_portal", () -> new AetherPortalBlock());
	public static final RegistryObject<Block> BLOCK_OF_THLINH_2 = REGISTRY.register("block_of_thlinh_2", () -> new BlockOfThlinh2Block());
	public static final RegistryObject<Block> BLOCK_OF_CHAU = REGISTRY.register("block_of_chau", () -> new BlockOfChauBlock());
	public static final RegistryObject<Block> BLOCK_OF_DANG_MINH = REGISTRY.register("block_of_dang_minh", () -> new BlockOfDangMinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_DANH = REGISTRY.register("block_of_danh", () -> new BlockOfDanhBlock());
	public static final RegistryObject<Block> BLOCK_OF_DAT = REGISTRY.register("block_of_dat", () -> new BlockOfDatBlock());
	public static final RegistryObject<Block> BLOCK_OF_DIEP = REGISTRY.register("block_of_diep", () -> new BlockOfDiepBlock());
	public static final RegistryObject<Block> BLOCK_OF_DUC_ANH = REGISTRY.register("block_of_duc_anh", () -> new BlockOfDucAnhBlock());
	public static final RegistryObject<Block> BLOCK_OF_DUONG = REGISTRY.register("block_of_duong", () -> new BlockOfDuongBlock());
	public static final RegistryObject<Block> BLOCK_OF_DUONG_MINH = REGISTRY.register("block_of_duong_minh", () -> new BlockOfDuongMinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_GIANG = REGISTRY.register("block_of_giang", () -> new BlockOfGiangBlock());
	public static final RegistryObject<Block> BLOCK_OF_HAI = REGISTRY.register("block_of_hai", () -> new BlockOfHaiBlock());
	public static final RegistryObject<Block> BLOCKOF_HA_MINH = REGISTRY.register("blockof_ha_minh", () -> new BlockofHaMinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_HOAI_AN = REGISTRY.register("block_of_hoai_an", () -> new BlockOfHoaiAnBlock());
	public static final RegistryObject<Block> BLOCK_OF_KHANH = REGISTRY.register("block_of_khanh", () -> new BlockOfKhanhBlock());
	public static final RegistryObject<Block> BLOCK_OF_KHANHS = REGISTRY.register("block_of_khanhs", () -> new BlockOfKhanhsBlock());
	public static final RegistryObject<Block> BLOCK_OF_KIEU_THAO = REGISTRY.register("block_of_kieu_thao", () -> new BlockOfKieuThaoBlock());
	public static final RegistryObject<Block> BLOCK_OF_LAM = REGISTRY.register("block_of_lam", () -> new BlockOfLamBlock());
	public static final RegistryObject<Block> BLOCK_OF_MY_AN = REGISTRY.register("block_of_my_an", () -> new BlockOfMyAnBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGAN = REGISTRY.register("block_of_ngan", () -> new BlockOfNganBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGOC_ANH = REGISTRY.register("block_of_ngoc_anh", () -> new BlockOfNgocAnhBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGUYEN_LINH = REGISTRY.register("block_of_nguyen_linh", () -> new BlockOfNguyenLinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGUYEN_MINH = REGISTRY.register("block_of_nguyen_minh", () -> new BlockOfNguyenMinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGUYEN_PHUC = REGISTRY.register("block_of_nguyen_phuc", () -> new BlockOfNguyenPhucBlock());
	public static final RegistryObject<Block> BLOCK_OF_NHAT_MINH = REGISTRY.register("block_of_nhat_minh", () -> new BlockOfNhatMinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_PHUONG = REGISTRY.register("block_of_phuong", () -> new BlockOfPhuongBlock());
	public static final RegistryObject<Block> BLOCK_OF_QUYNH = REGISTRY.register("block_of_quynh", () -> new BlockOfQuynhBlock());
	public static final RegistryObject<Block> BLOCK_OF_TAI = REGISTRY.register("block_of_tai", () -> new BlockOfTaiBlock());
	public static final RegistryObject<Block> BLOCK_OF_THAI = REGISTRY.register("block_of_thai", () -> new BlockOfThaiBlock());
	public static final RegistryObject<Block> BLOCK_OF_THANH = REGISTRY.register("block_of_thanh", () -> new BlockOfThanhBlock());
	public static final RegistryObject<Block> BLOCK_OF_THLINH = REGISTRY.register("block_of_thlinh", () -> new BlockOfThlinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_TPLINH = REGISTRY.register("block_of_tplinh", () -> new BlockOfTplinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_TRUC = REGISTRY.register("block_of_truc", () -> new BlockOfTrucBlock());
	public static final RegistryObject<Block> BLOCK_OF_UYEN = REGISTRY.register("block_of_uyen", () -> new BlockOfUyenBlock());
	public static final RegistryObject<Block> BLOCK_OF_VHLINH = REGISTRY.register("block_of_vhlinh", () -> new BlockOfVhlinhBlock());
	public static final RegistryObject<Block> BLOCK_OF_VU_THAO = REGISTRY.register("block_of_vu_thao", () -> new BlockOfVuThaoBlock());
	public static final RegistryObject<Block> BLOCK_OF_NGUYEN = REGISTRY.register("block_of_nguyen", () -> new BlockOfNguyenBlock());
	public static final RegistryObject<Block> BLOCK_OF_DHP = REGISTRY.register("block_of_dhp", () -> new BlockOfDHPBlock());
	public static final RegistryObject<Block> BLOCK_OF_CO_TOAN = REGISTRY.register("block_of_co_toan", () -> new BlockOfCoToanBlock());
	public static final RegistryObject<Block> K_7_A_2_LAVA = REGISTRY.register("k_7_a_2_lava", () -> new K7A2LavaBlock());
	public static final RegistryObject<Block> K_7_A_2_FLOWER = REGISTRY.register("k_7_a_2_flower", () -> new K7A2FlowerBlock());
	public static final RegistryObject<Block> K_7_A_2_RAINBOW_BLOCK = REGISTRY.register("k_7_a_2_rainbow_block", () -> new K7A2RainbowBlockBlock());
	public static final RegistryObject<Block> K_7_A_2_RAINBOW_DECORATION_BLOCK = REGISTRY.register("k_7_a_2_rainbow_decoration_block", () -> new K7A2RainbowDecorationBlockBlock());
	public static final RegistryObject<Block> K_7_A_2_SECRET_DECORATION = REGISTRY.register("k_7_a_2_secret_decoration", () -> new K7A2SecretDecorationBlock());
}
