/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package mc.dhp.foss.k7a2.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import mc.dhp.foss.k7a2.item.ThienLyOiItem;
import mc.dhp.foss.k7a2.item.TNTChargeItem;
import mc.dhp.foss.k7a2.item.TNTBowItem;
import mc.dhp.foss.k7a2.item.TNTArrowItem;
import mc.dhp.foss.k7a2.item.SuperK7A2IngotItem;
import mc.dhp.foss.k7a2.item.SmurfcatItem;
import mc.dhp.foss.k7a2.item.RawK7A2EnchantedAppleItem;
import mc.dhp.foss.k7a2.item.OldNetheriteSpammableSwordItem;
import mc.dhp.foss.k7a2.item.OPBowItem;
import mc.dhp.foss.k7a2.item.NightChangeItem;
import mc.dhp.foss.k7a2.item.MaGamingRapItem;
import mc.dhp.foss.k7a2.item.K7a2mixeddiscItem;
import mc.dhp.foss.k7a2.item.K7A2ingotItem;
import mc.dhp.foss.k7a2.item.K7A2ToolGettingBlockItem;
import mc.dhp.foss.k7a2.item.K7A2SwordItem;
import mc.dhp.foss.k7a2.item.K7A2StickItem;
import mc.dhp.foss.k7a2.item.K7A2ShovelItem;
import mc.dhp.foss.k7a2.item.K7A2ShearsItem;
import mc.dhp.foss.k7a2.item.K7A2PickaxeItem;
import mc.dhp.foss.k7a2.item.K7A2NuggetItem;
import mc.dhp.foss.k7a2.item.K7A2LavaItem;
import mc.dhp.foss.k7a2.item.K7A2HoeItem;
import mc.dhp.foss.k7a2.item.K7A2EnchantedAppleItem;
import mc.dhp.foss.k7a2.item.K7A2DimItem;
import mc.dhp.foss.k7a2.item.K7A2CarrotItem;
import mc.dhp.foss.k7a2.item.K7A2AxeItem;
import mc.dhp.foss.k7a2.item.K7A2ArmorItem;
import mc.dhp.foss.k7a2.item.K7A2AppleItem;
import mc.dhp.foss.k7a2.item.IfIAmWithYouItem;
import mc.dhp.foss.k7a2.item.HanhKhucCBHItem;
import mc.dhp.foss.k7a2.item.FlorentinoItem;
import mc.dhp.foss.k7a2.item.EndermanSecretItem;
import mc.dhp.foss.k7a2.item.EndermanHackWindows10SItem;
import mc.dhp.foss.k7a2.item.DeathNoteItem;
import mc.dhp.foss.k7a2.item.DeadlyBowItem;
import mc.dhp.foss.k7a2.item.BuonHayVuiItem;
import mc.dhp.foss.k7a2.item.BedrockInstantMinePickaxeItem;
import mc.dhp.foss.k7a2.item.BattleGoldenAxeItem;
import mc.dhp.foss.k7a2.item.AetherItem;
import mc.dhp.foss.k7a2.K7a2Mod;

public class K7a2ModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, K7a2Mod.MODID);
	public static final RegistryObject<Item> TRAN_HOAI_AN_SPAWN_EGG = REGISTRY.register("tran_hoai_an_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_HOAI_AN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PHAM_MY_AN_SPAWN_EGG = REGISTRY.register("pham_my_an_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.PHAM_MY_AN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_THI_NGOC_ANH_SPAWN_EGG = REGISTRY.register("nguyen_thi_ngoc_anh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_THI_NGOC_ANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DINH_DIEP_ANH_SPAWN_EGG = REGISTRY.register("dinh_diep_anh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.DINH_DIEP_ANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PHAM_DUC_ANH_SPAWN_EGG = REGISTRY.register("pham_duc_anh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.PHAM_DUC_ANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_PHAM_MINH_CHAU_SPAWN_EGG = REGISTRY.register("nguyen_pham_minh_chau_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_PHAM_MINH_CHAU, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRUONG_NGOC_DIEP_SPAWN_EGG = REGISTRY.register("truong_ngoc_diep_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRUONG_NGOC_DIEP, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DINH_HOANG_DUONG_SPAWN_EGG = REGISTRY.register("dinh_hoang_duong_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.DINH_HOANG_DUONG, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> LUONG_HUU_DAT_SPAWN_EGG = REGISTRY.register("luong_huu_dat_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.LUONG_HUU_DAT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_KHANH_GIANG_SPAWN_EGG = REGISTRY.register("tran_khanh_giang_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_KHANH_GIANG, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> HOANG_DUC_HAI_SPAWN_EGG = REGISTRY.register("hoang_duc_hai_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.HOANG_DUC_HAI, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_LE_KHANH_SPAWN_EGG = REGISTRY.register("nguyen_le_khanh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_LE_KHANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_NAM_KHANH_SPAWN_EGG = REGISTRY.register("nguyen_nam_khanh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_NAM_KHANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_TUNG_LAM_SPAWN_EGG = REGISTRY.register("nguyen_tung_lam_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_TUNG_LAM, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_HA_LINH_SPAWN_EGG = REGISTRY.register("tran_ha_linh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_HA_LINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_PHUONG_LINH_SPAWN_EGG = REGISTRY.register("tran_phuong_linh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_PHUONG_LINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_PHUONG_LINH_SPAWN_EGG = REGISTRY.register("nguyen_phuong_linh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_PHUONG_LINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> VU_HA_LINH_SPAWN_EGG = REGISTRY.register("vu_ha_linh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.VU_HA_LINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> K_7_A_2INGOT = REGISTRY.register("k_7_a_2ingot", () -> new K7A2ingotItem());
	public static final RegistryObject<Item> NGUYEN_TUAN_MINH_SPAWN_EGG = REGISTRY.register("nguyen_tuan_minh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_TUAN_MINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DUONG_TIEN_MINH_SPAWN_EGG = REGISTRY.register("duong_tien_minh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.DUONG_TIEN_MINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DANG_TUAN_MINH_SPAWN_EGG = REGISTRY.register("dang_tuan_minh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.DANG_TUAN_MINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_HA_MINH_SPAWN_EGG = REGISTRY.register("nguyen_ha_minh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_HA_MINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_NHAT_MINH_SPAWN_EGG = REGISTRY.register("tran_nhat_minh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_NHAT_MINH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> K_7_A_2_NUGGET = REGISTRY.register("k_7_a_2_nugget", () -> new K7A2NuggetItem());
	public static final RegistryObject<Item> VU_KHANH_NGAN_SPAWN_EGG = REGISTRY.register("vu_khanh_ngan_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.VU_KHANH_NGAN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_KHOI_NGUYEN_SPAWN_EGG = REGISTRY.register("nguyen_khoi_nguyen_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_KHOI_NGUYEN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_LAP_HONG_PHUC_SPAWN_EGG = REGISTRY.register("nguyen_lap_hong_phuc_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_LAP_HONG_PHUC, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_MAI_PHUONG_SPAWN_EGG = REGISTRY.register("tran_mai_phuong_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_MAI_PHUONG, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_NHU_QUYNH_SPAWN_EGG = REGISTRY.register("tran_nhu_quynh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_NHU_QUYNH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DO_DUC_ANH_TAI_SPAWN_EGG = REGISTRY.register("do_duc_anh_tai_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.DO_DUC_ANH_TAI, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TRAN_QUY_HOANG_THAI_SPAWN_EGG = REGISTRY.register("tran_quy_hoang_thai_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TRAN_QUY_HOANG_THAI, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_TUAN_THANH_SPAWN_EGG = REGISTRY.register("nguyen_tuan_thanh_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_TUAN_THANH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> VU_THANH_THAO_SPAWN_EGG = REGISTRY.register("vu_thanh_thao_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.VU_THANH_THAO, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> KIEU_PHUONG_THAO_SPAWN_EGG = REGISTRY.register("kieu_phuong_thao_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.KIEU_PHUONG_THAO, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_THANH_TRUC_SPAWN_EGG = REGISTRY.register("nguyen_thanh_truc_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_THANH_TRUC, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NGUYEN_TU_UYEN_SPAWN_EGG = REGISTRY.register("nguyen_tu_uyen_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.NGUYEN_TU_UYEN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BLOCKOF_K_7_A_2 = block(K7a2ModBlocks.BLOCKOF_K_7_A_2);
	public static final RegistryObject<Item> K_7_A_2_ARMOR_HELMET = REGISTRY.register("k_7_a_2_armor_helmet", () -> new K7A2ArmorItem.Helmet());
	public static final RegistryObject<Item> K_7_A_2_ARMOR_CHESTPLATE = REGISTRY.register("k_7_a_2_armor_chestplate", () -> new K7A2ArmorItem.Chestplate());
	public static final RegistryObject<Item> K_7_A_2_ARMOR_LEGGINGS = REGISTRY.register("k_7_a_2_armor_leggings", () -> new K7A2ArmorItem.Leggings());
	public static final RegistryObject<Item> K_7_A_2_ARMOR_BOOTS = REGISTRY.register("k_7_a_2_armor_boots", () -> new K7A2ArmorItem.Boots());
	public static final RegistryObject<Item> K_7_A_2_PICKAXE = REGISTRY.register("k_7_a_2_pickaxe", () -> new K7A2PickaxeItem());
	public static final RegistryObject<Item> K_7_A_2_AXE = REGISTRY.register("k_7_a_2_axe", () -> new K7A2AxeItem());
	public static final RegistryObject<Item> K_7_A_2_SHOVEL = REGISTRY.register("k_7_a_2_shovel", () -> new K7A2ShovelItem());
	public static final RegistryObject<Item> K_7_A_2_HOE = REGISTRY.register("k_7_a_2_hoe", () -> new K7A2HoeItem());
	public static final RegistryObject<Item> K_7_A_2_SWORD = REGISTRY.register("k_7_a_2_sword", () -> new K7A2SwordItem());
	public static final RegistryObject<Item> SUPER_K_7_A_2_INGOT = REGISTRY.register("super_k_7_a_2_ingot", () -> new SuperK7A2IngotItem());
	public static final RegistryObject<Item> K_7_A_2_STICK = REGISTRY.register("k_7_a_2_stick", () -> new K7A2StickItem());
	public static final RegistryObject<Item> K_7_A_2_SHEARS = REGISTRY.register("k_7_a_2_shears", () -> new K7A2ShearsItem());
	public static final RegistryObject<Item> RAW_K_7_A_2_ENCHANTED_APPLE = REGISTRY.register("raw_k_7_a_2_enchanted_apple", () -> new RawK7A2EnchantedAppleItem());
	public static final RegistryObject<Item> OLD_NETHERITE_SPAMMABLE_SWORD = REGISTRY.register("old_netherite_spammable_sword", () -> new OldNetheriteSpammableSwordItem());
	public static final RegistryObject<Item> BATTLE_GOLDEN_AXE = REGISTRY.register("battle_golden_axe", () -> new BattleGoldenAxeItem());
	public static final RegistryObject<Item> DEATH_NOTE = REGISTRY.register("death_note", () -> new DeathNoteItem());
	public static final RegistryObject<Item> TOAN_SPAWN_EGG = REGISTRY.register("toan_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.TOAN, -6750208, -65419, new Item.Properties()));
	public static final RegistryObject<Item> K_7_A_2_WOOD_WOOD = block(K7a2ModBlocks.K_7_A_2_WOOD_WOOD);
	public static final RegistryObject<Item> K_7_A_2_WOOD_LOG = block(K7a2ModBlocks.K_7_A_2_WOOD_LOG);
	public static final RegistryObject<Item> K_7_A_2_WOOD_PLANKS = block(K7a2ModBlocks.K_7_A_2_WOOD_PLANKS);
	public static final RegistryObject<Item> K_7_A_2_WOOD_LEAVES = block(K7a2ModBlocks.K_7_A_2_WOOD_LEAVES);
	public static final RegistryObject<Item> K_7_A_2_WOOD_STAIRS = block(K7a2ModBlocks.K_7_A_2_WOOD_STAIRS);
	public static final RegistryObject<Item> K_7_A_2_WOOD_SLAB = block(K7a2ModBlocks.K_7_A_2_WOOD_SLAB);
	public static final RegistryObject<Item> K_7_A_2_WOOD_FENCE = block(K7a2ModBlocks.K_7_A_2_WOOD_FENCE);
	public static final RegistryObject<Item> K_7_A_2_WOOD_FENCE_GATE = block(K7a2ModBlocks.K_7_A_2_WOOD_FENCE_GATE);
	public static final RegistryObject<Item> K_7_A_2_PORTAL_BLOCK = block(K7a2ModBlocks.K_7_A_2_PORTAL_BLOCK);
	public static final RegistryObject<Item> K_7_A_2_DIM = REGISTRY.register("k_7_a_2_dim", () -> new K7A2DimItem());
	public static final RegistryObject<Item> DH_PHUC_WOOD = block(K7a2ModBlocks.DH_PHUC_WOOD);
	public static final RegistryObject<Item> DH_PHUC_LOG = block(K7a2ModBlocks.DH_PHUC_LOG);
	public static final RegistryObject<Item> DH_PHUC_PLANKS = block(K7a2ModBlocks.DH_PHUC_PLANKS);
	public static final RegistryObject<Item> DH_PHUC_LEAVES = block(K7a2ModBlocks.DH_PHUC_LEAVES);
	public static final RegistryObject<Item> DH_PHUC_STAIRS = block(K7a2ModBlocks.DH_PHUC_STAIRS);
	public static final RegistryObject<Item> DH_PHUC_SLAB = block(K7a2ModBlocks.DH_PHUC_SLAB);
	public static final RegistryObject<Item> DH_PHUC_FENCE = block(K7a2ModBlocks.DH_PHUC_FENCE);
	public static final RegistryObject<Item> DH_PHUC_FENCE_GATE = block(K7a2ModBlocks.DH_PHUC_FENCE_GATE);
	public static final RegistryObject<Item> AETHER = REGISTRY.register("aether", () -> new AetherItem());
	public static final RegistryObject<Item> BLOCK_OF_THLINH_2 = block(K7a2ModBlocks.BLOCK_OF_THLINH_2);
	public static final RegistryObject<Item> BLOCK_OF_CHAU = block(K7a2ModBlocks.BLOCK_OF_CHAU);
	public static final RegistryObject<Item> BLOCK_OF_DANG_MINH = block(K7a2ModBlocks.BLOCK_OF_DANG_MINH);
	public static final RegistryObject<Item> BLOCK_OF_DANH = block(K7a2ModBlocks.BLOCK_OF_DANH);
	public static final RegistryObject<Item> BLOCK_OF_DAT = block(K7a2ModBlocks.BLOCK_OF_DAT);
	public static final RegistryObject<Item> BLOCK_OF_DIEP = block(K7a2ModBlocks.BLOCK_OF_DIEP);
	public static final RegistryObject<Item> BLOCK_OF_DUC_ANH = block(K7a2ModBlocks.BLOCK_OF_DUC_ANH);
	public static final RegistryObject<Item> BLOCK_OF_DUONG = block(K7a2ModBlocks.BLOCK_OF_DUONG);
	public static final RegistryObject<Item> BLOCK_OF_DUONG_MINH = block(K7a2ModBlocks.BLOCK_OF_DUONG_MINH);
	public static final RegistryObject<Item> BLOCK_OF_GIANG = block(K7a2ModBlocks.BLOCK_OF_GIANG);
	public static final RegistryObject<Item> BLOCK_OF_HAI = block(K7a2ModBlocks.BLOCK_OF_HAI);
	public static final RegistryObject<Item> BLOCKOF_HA_MINH = block(K7a2ModBlocks.BLOCKOF_HA_MINH);
	public static final RegistryObject<Item> BLOCK_OF_HOAI_AN = block(K7a2ModBlocks.BLOCK_OF_HOAI_AN);
	public static final RegistryObject<Item> BLOCK_OF_KHANH = block(K7a2ModBlocks.BLOCK_OF_KHANH);
	public static final RegistryObject<Item> BLOCK_OF_KHANHS = block(K7a2ModBlocks.BLOCK_OF_KHANHS);
	public static final RegistryObject<Item> BLOCK_OF_KIEU_THAO = block(K7a2ModBlocks.BLOCK_OF_KIEU_THAO);
	public static final RegistryObject<Item> BLOCK_OF_LAM = block(K7a2ModBlocks.BLOCK_OF_LAM);
	public static final RegistryObject<Item> BLOCK_OF_MY_AN = block(K7a2ModBlocks.BLOCK_OF_MY_AN);
	public static final RegistryObject<Item> BLOCK_OF_NGAN = block(K7a2ModBlocks.BLOCK_OF_NGAN);
	public static final RegistryObject<Item> BLOCK_OF_NGOC_ANH = block(K7a2ModBlocks.BLOCK_OF_NGOC_ANH);
	public static final RegistryObject<Item> BLOCK_OF_NGUYEN_LINH = block(K7a2ModBlocks.BLOCK_OF_NGUYEN_LINH);
	public static final RegistryObject<Item> BLOCK_OF_NGUYEN_MINH = block(K7a2ModBlocks.BLOCK_OF_NGUYEN_MINH);
	public static final RegistryObject<Item> BLOCK_OF_NGUYEN_PHUC = block(K7a2ModBlocks.BLOCK_OF_NGUYEN_PHUC);
	public static final RegistryObject<Item> BLOCK_OF_NHAT_MINH = block(K7a2ModBlocks.BLOCK_OF_NHAT_MINH);
	public static final RegistryObject<Item> BLOCK_OF_PHUONG = block(K7a2ModBlocks.BLOCK_OF_PHUONG);
	public static final RegistryObject<Item> BLOCK_OF_QUYNH = block(K7a2ModBlocks.BLOCK_OF_QUYNH);
	public static final RegistryObject<Item> BLOCK_OF_TAI = block(K7a2ModBlocks.BLOCK_OF_TAI);
	public static final RegistryObject<Item> BLOCK_OF_THAI = block(K7a2ModBlocks.BLOCK_OF_THAI);
	public static final RegistryObject<Item> BLOCK_OF_THANH = block(K7a2ModBlocks.BLOCK_OF_THANH);
	public static final RegistryObject<Item> BLOCK_OF_THLINH = block(K7a2ModBlocks.BLOCK_OF_THLINH);
	public static final RegistryObject<Item> BLOCK_OF_TPLINH = block(K7a2ModBlocks.BLOCK_OF_TPLINH);
	public static final RegistryObject<Item> BLOCK_OF_TRUC = block(K7a2ModBlocks.BLOCK_OF_TRUC);
	public static final RegistryObject<Item> BLOCK_OF_UYEN = block(K7a2ModBlocks.BLOCK_OF_UYEN);
	public static final RegistryObject<Item> BLOCK_OF_VHLINH = block(K7a2ModBlocks.BLOCK_OF_VHLINH);
	public static final RegistryObject<Item> BLOCK_OF_VU_THAO = block(K7a2ModBlocks.BLOCK_OF_VU_THAO);
	public static final RegistryObject<Item> BLOCK_OF_NGUYEN = block(K7a2ModBlocks.BLOCK_OF_NGUYEN);
	public static final RegistryObject<Item> BLOCK_OF_DHP = block(K7a2ModBlocks.BLOCK_OF_DHP);
	public static final RegistryObject<Item> BLOCK_OF_CO_TOAN = block(K7a2ModBlocks.BLOCK_OF_CO_TOAN);
	public static final RegistryObject<Item> BEDROCK_INSTANT_MINE_PICKAXE = REGISTRY.register("bedrock_instant_mine_pickaxe", () -> new BedrockInstantMinePickaxeItem());
	public static final RegistryObject<Item> K_7_A_2_TOOL_GETTING_BLOCK = REGISTRY.register("k_7_a_2_tool_getting_block", () -> new K7A2ToolGettingBlockItem());
	public static final RegistryObject<Item> K_7_A_2_APPLE = REGISTRY.register("k_7_a_2_apple", () -> new K7A2AppleItem());
	public static final RegistryObject<Item> K_7_A_2_ENCHANTED_APPLE = REGISTRY.register("k_7_a_2_enchanted_apple", () -> new K7A2EnchantedAppleItem());
	public static final RegistryObject<Item> K_7_A_2_CARROT = REGISTRY.register("k_7_a_2_carrot", () -> new K7A2CarrotItem());
	public static final RegistryObject<Item> K_7_A_2_LAVA_BUCKET = REGISTRY.register("k_7_a_2_lava_bucket", () -> new K7A2LavaItem());
	public static final RegistryObject<Item> K_7_A_2_FLOWER = block(K7a2ModBlocks.K_7_A_2_FLOWER);
	public static final RegistryObject<Item> K_7_A_2_RAINBOW_BLOCK = block(K7a2ModBlocks.K_7_A_2_RAINBOW_BLOCK);
	public static final RegistryObject<Item> K_7_A_2_RAINBOW_DECORATION_BLOCK = block(K7a2ModBlocks.K_7_A_2_RAINBOW_DECORATION_BLOCK);
	public static final RegistryObject<Item> PHAN_SPAWN_EGG = REGISTRY.register("phan_spawn_egg", () -> new ForgeSpawnEggItem(K7a2ModEntities.PHAN, -3480320, -16449536, new Item.Properties()));
	public static final RegistryObject<Item> K_7_A_2_SECRET_DECORATION = block(K7a2ModBlocks.K_7_A_2_SECRET_DECORATION);
	public static final RegistryObject<Item> TNT_ARROW = REGISTRY.register("tnt_arrow", () -> new TNTArrowItem());
	public static final RegistryObject<Item> TNT_CHARGE = REGISTRY.register("tnt_charge", () -> new TNTChargeItem());
	public static final RegistryObject<Item> OP_BOW = REGISTRY.register("op_bow", () -> new OPBowItem());
	public static final RegistryObject<Item> DEADLY_BOW = REGISTRY.register("deadly_bow", () -> new DeadlyBowItem());
	public static final RegistryObject<Item> TNT_BOW = REGISTRY.register("tnt_bow", () -> new TNTBowItem());
	public static final RegistryObject<Item> HANH_KHUC_CBH = REGISTRY.register("hanh_khuc_cbh", () -> new HanhKhucCBHItem());
	public static final RegistryObject<Item> MA_GAMING_RAP = REGISTRY.register("ma_gaming_rap", () -> new MaGamingRapItem());
	public static final RegistryObject<Item> FLORENTINO = REGISTRY.register("florentino", () -> new FlorentinoItem());
	public static final RegistryObject<Item> THIEN_LY_OI = REGISTRY.register("thien_ly_oi", () -> new ThienLyOiItem());
	public static final RegistryObject<Item> IF_I_AM_WITH_YOU = REGISTRY.register("if_i_am_with_you", () -> new IfIAmWithYouItem());
	public static final RegistryObject<Item> SMURFCAT = REGISTRY.register("smurfcat", () -> new SmurfcatItem());
	public static final RegistryObject<Item> K_7A_2MIXEDDISC = REGISTRY.register("k_7a_2mixeddisc", () -> new K7a2mixeddiscItem());
	public static final RegistryObject<Item> ENDERMAN_HACK_WINDOWS_10_S = REGISTRY.register("enderman_hack_windows_10_s", () -> new EndermanHackWindows10SItem());
	public static final RegistryObject<Item> ENDERMAN_SECRET = REGISTRY.register("enderman_secret", () -> new EndermanSecretItem());
	public static final RegistryObject<Item> BUON_HAY_VUI = REGISTRY.register("buon_hay_vui", () -> new BuonHayVuiItem());
	public static final RegistryObject<Item> NIGHT_CHANGE = REGISTRY.register("night_change", () -> new NightChangeItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}