modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="k7a2"
version="14.1"
displayName="k7a2"
displayURL="https://phucdh0110.localplayer.dev"
logoFile="logo.png"
credits="Thanks all of you for playing , testing and contributing"
authors="Dao Hong Phuc"
description="K7A2 CBH mod made to be working on MC. Rebuilt from 1.19.4"

[[dependencies.k7a2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




